### PR TITLE
Added new blog with getting started resources

### PR DESCRIPTION
**Pull request by kmugrage**

### CODE REVIEW

**Comment by arvindsv** [comment]
I like this. I think it can be a good go-to page. Hypothetically, if I were to update some getting started resources, which one/ones would you want me to work on.

**Comment by kmugrage** [comment]
Good question, but I'm not sure. Have you / we noticed any patterns of people getting stuck?

**Comment by arvindsv** [comment]
Yes, there are some I see people struggle with. The concepts of agent vs. server, where the checkout happens, environment variables, etc. I am thinking about reworking the concepts page and some advanced topics.

**Comment by nhudacin** [comment]
I like this a lot too!! I'm always looking for resources, how-to's, and blogs about Go. It would be nice to have a page devoted to some "must-read" content about getting up and running. I started using Go about two months ago and would have loved to see this page then.

**Comment by kmugrage** [comment]
Unless there's anything inaccurate here I'd request we merge it. We can always add more.

**Comment by ketan** [comment]
I don't see anything inaccurate here. We donrlt have enough eyeballs to merge this. So if you can merge it, that'll be great.

**Comment by ketan** [comment]
@arvindsv - how do we get this blog published?

**Comment by kmugrage** [comment]
We merge it, which I already did :)

On Thu, May 14, 2015 at 10:18 AM, Ketan Padegaonkar <
notifications@github.com> wrote:

> @arvindsv <https://github.com/arvindsv> - how do we get this blog
> published?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocd/gocd.github.io/pull/156#issuecomment-102106861>.
>



-- 
Ken Mugrage - ThoughtWorks Studioskmugrage@thoughtworks.com+1(425) 835-3056
@kmugrage

**Pull request merged**
