### PR TITLE
Add a feature toggle based renderer based off the new release.json files from a different url.

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by arvindsv** [comment]
The experimental releases list need to be reversed. The oldest one shows up first.

**Comment by arvindsv** [comment]
Maybe you already fixed it. Will check this version again.

**Comment by arvindsv** [comment]
Yeah, [this reverse here](https://github.com/gocd/gocd.github.io/pull/250/files#diff-ca712f57d34961d7758c88e51edc9583R88) is messing up the order of the experimental revisions.

**Comment by ketan** [comment]
I cleaned up the sorting in another changeset. I'm now sorting both supported and unsupported releases and reversing them in one place — works consistently with and without the toggle.

**Pull request merged**
