### PR TITLE
Adding S3 artifacts plugins

### PR DESCRIPTION
**Pull request by manojlds**

### CODE REVIEW

**Comment by jyotisingh** [comment]
Why don't you submit this for [go plugin challenge](http://info.thoughtworks.com/go-plugin-challenge-registration-page-20-jan-2015.html)? Just four more days to go!

**Comment by manojlds** [comment]
@jyotisingh  Isn't sending this PR the requirement for the challenge? :)

**Comment by jyotisingh** [comment]
@manojlds - Yes it is. I believe there is a form to be filled as well :)

**Comment by manojlds** [comment]
Is this being merged?

BTW, the docs are here - http://ind9.github.io/gocd-s3-artifacts/

Hoping for feedback.

**Pull request merged**
