### PR TITLE
Add Go.CD TLS Auth plugin to plugins list

### PR DESCRIPTION
**Pull request by cnorthwood**

### CODE REVIEW

**Comment by ketan** [comment]
Hi —

Would you mind signing the [CLA](https://www.go.cd/contribute/cla.html)? It's a one time requirement.

:+1:

**Comment by cnorthwood** [comment]
Done :)

**Comment by ketan** [comment]
It should be live in a few minutes on the plugins page.

**Comment by cnorthwood** [comment]
this seems to have disappeared :( lost in a merge, or should I resubmit it?

**Comment by arvindsv** [comment]
:( Damn. Let me see what happened.

**Comment by arvindsv** [comment]
I see it's missing. Don't know why yet. I'll bring it over from the old site and check all other plugins as well.

**Comment by arvindsv** [comment]
@cnorthwood: Thanks for this. I found 5 other plugins which were not moved over. This seems to have happened because the plugins were added to the old site, but the data was copied over earlier than that. It should all be consistent now. The change will propagate across the edge servers and you should be able to see it soon. Sorry about that.

**Pull request merged**
