### PR TITLE
Added a Windows PowerShell blog post

### PR DESCRIPTION
**Pull request by pmcgrath**
Added a post that gives some background\preparation for running PowerShell tasks on a Go Agent
Added some content on propogating errors within a PowerShell script

### CODE REVIEW

**Comment by kmugrage** [comment]
@pmcgrath - thanks for the submission!

@arvindsv - this looks good to me, can you please review?

**Comment by arvindsv** [comment]
Hi @pmcgrath, I think this is good. I've made some small, [mostly cosmetic changes](https://github.com/arvindsv/gocd.github.io/commit/e17a7595c6ae43312281727d9e507735fb0c456a) to it. Can you take a look and tell me if you're ok with it?

Also, if you are ok with it, I think it would be nice to have some information about you somewhere in the page. In case you're ok with that, let me know. If not, maybe I can at least link to your GitHub profile?

Here are a couple of images of the page before and after my changes:

#### Before:

old

#### After:

new

**Comment by pmcgrath** [comment]
@arvindsv Your changes are fine with me, I merged them into by fork and have also added the following changes
- Fixed a spelling mistake
- Removed the <p> tag that had no closing </p> - You can undo this if you think it should be left in there

One other change I could make is to make all text references to "Go agent" become "Go Agent" so it is consistent within the post, leave me know.

I checked other posts and didn't find any previous content on a guest poster, so I don't really know what to put in regarding myself, happy enough for you to put a link to my github profile.

Pat

**Comment by pmcgrath** [comment]
Just seen that the tag I referred to is being literally inlined - I was referring to a p tag

**Comment by arvindsv** [comment]
> I checked other posts and didn't find any previous content on a guest poster, so I don't really know what to put in regarding myself, happy enough for you to put a link to my github profile.

I don't think we've ever marked a post as "Guest post". I just did that to see how it looks. I think it's nice. Let's try it. I'll add a link to your GitHub profile and merge it.

**Comment by pmcgrath** [comment]
Sounds good to me

**Comment by arvindsv** [comment]
Thanks again! This is going to be useful to many others, I'm sure. It's [up](http://www.go.cd/2015/06/13/using-windows-powershell-tasks.html).

**Pull request merged**
