### PR TITLE
First in a blog series about types of pipelines

### PR DESCRIPTION
**Pull request by kmugrage**
Committing without images since there's not currently a defined way to float images on the go.cd blog

### CODE REVIEW

**Comment by arvindsv** [comment]
If you'd like me to help you with it, let me know. We might need to make some of the sections HTML instead of markdown, but that's easy.

**Comment by kmugrage** [comment]
That would be great if you have time, but Jen M suggests we merge without images now since we want to get the series published.

**Comment by arvindsv** [comment]
Ok. Looking at it now. I'll time box it to a few minutes and see what I can get.

**Comment by arvindsv** [comment]
I just need to know where those images should be.

**Comment by arvindsv** [comment]
If you really want me to merge it in, without that, that's fine too. Just let me know if you're sure.

**Pull request merged**
