### PR TITLE
Added docker pipeline plugin

### PR DESCRIPTION
**Pull request by bradeac**

### CODE REVIEW

**Comment by ketan** [comment]
Could you resolve the merge conflicts so we can merge?

**Comment by bradeac** [comment]
Hello Ketan,

No more conflicts now.

Thank you.

**Comment by ketan** [comment]
You'll see this published in around 10-20 minutes depending on the CDN :)

**Comment by bradeac** [comment]
It's already there. The description is too long, and it covers the "Read more" link, so I should shorten the description and push the changes. So I should create a new pull request for that ?

**Comment by ketan** [comment]
Yes please, new PR.

**Comment by bradeac** [comment]
Ok, I've created it.

Thank you.

**Pull request merged**
